#!/usr/bin/env python3
"""
============================================================================
 ChronoChip AI :: Smart Fab & Geopolitical Risk Copilot
 IBM Bob Innovation Hackathon 2026 — Problem Statement S2 (Semiconductor)
============================================================================

ARCHITECTURE
------------
ChronoChip AI is implemented as a lightweight, dependency-free Model
Context Protocol (MCP) style tool server. It exposes four callable tools
that an IBM Bob Agent (or any LLM orchestrator) can invoke over stdio /
function-calling:

    fab.get_wip_telemetry        -> live WIP snapshot across Litho/Etch/CVD
    fab.predict_bottleneck       -> X-factor based delay + 52wk propagation
    geo.assess_material_risk     -> single-source HHI risk matrix
    bob.ask                      -> natural-language copilot over the above

No third-party packages are required (stdlib only), so it runs anywhere
in under a second and is safe to demo live. All numbers are generated by
a seeded, physically-plausible stochastic model (not literal fab data),
tuned to real-world fab engineering ranges (X-factor, OEE, Q-time, HHI).

Author: ChronoChip AI Team — IBM Bob Innovation Hackathon 2026
============================================================================
"""

from __future__ import annotations

import random
import shutil
import sys
import time
import textwrap
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Callable


# ============================================================================
# SECTION 0 — TERMINAL RENDERING KERNEL (pure-stdlib "rich" replacement)
# ============================================================================

class C:
    """ANSI color/style kernel. No external deps -> zero install risk on demo day."""
    RESET   = "\033[0m"
    BOLD    = "\033[1m"
    DIM     = "\033[2m"
    ITALIC  = "\033[3m"
    UNDER   = "\033[4m"

    FG_CYAN    = "\033[38;5;51m"
    FG_TEAL    = "\033[38;5;44m"
    FG_BLUE    = "\033[38;5;39m"
    FG_INDIGO  = "\033[38;5;99m"
    FG_GREEN   = "\033[38;5;46m"
    FG_AMBER   = "\033[38;5;214m"
    FG_RED     = "\033[38;5;196m"
    FG_MAGENTA = "\033[38;5;201m"
    FG_GREY    = "\033[38;5;245m"
    FG_WHITE   = "\033[38;5;255m"

    BG_DARK    = "\033[48;5;235m"

    @staticmethod
    def wrap(text: str, *codes: str) -> str:
        return f"{''.join(codes)}{text}{C.RESET}"


def term_width(default: int = 96) -> int:
    try:
        w = shutil.get_terminal_size(fallback=(default, 24)).columns
        return max(80, min(w, 120))
    except Exception:
        return default


def hr(char: str = "─", color: str = C.FG_GREY) -> str:
    return C.wrap(char * term_width(), color)


def panel(title: str, lines: list[str], color: str = C.FG_CYAN, icon: str = "◆") -> str:
    """Render a box-drawn panel with a titled header — the visual signature of the CLI."""
    w = term_width()
    inner = w - 2
    top = f"{color}╭{'─' * inner}╮{C.RESET}"
    title_line = f" {icon} {C.BOLD}{title}{C.RESET}{color}"
    pad = inner - len(f" {icon} {title}") 
    title_row = f"{color}│{C.RESET}{title_line}{' ' * max(pad, 0)}{color}│{C.RESET}"
    sep = f"{color}├{'─' * inner}┤{C.RESET}"
    body = []
    for ln in lines:
        for wrapped in (textwrap.wrap(ln, inner - 2) or [""]):
            pad2 = inner - 2 - len(_strip_ansi(wrapped))
            body.append(f"{color}│{C.RESET} {wrapped}{' ' * max(pad2, 0)} {color}│{C.RESET}")
    bottom = f"{color}╰{'─' * inner}╯{C.RESET}"
    return "\n".join([top, title_row, sep, *body, bottom])


def _strip_ansi(s: str) -> str:
    import re
    return re.sub(r"\033\[[0-9;]*m", "", s)


def table(headers: list[str], rows: list[list[str]], widths: list[int] | None = None,
          accent: str = C.FG_TEAL) -> str:
    if widths is None:
        widths = []
        for i, h in enumerate(headers):
            col = [h] + [str(r[i]) for r in rows]
            widths.append(max(len(_strip_ansi(c)) for c in col) + 2)

    def fmt_row(cells: list[str]) -> str:
        out = []
        for c_, w in zip(cells, widths):
            pad = w - len(_strip_ansi(c_))
            out.append(c_ + " " * max(pad, 0))
        return "│ " + " │ ".join(out) + " │"

    top = "╭" + "┬".join("─" * (w + 2) for w in widths) + "╮"
    sep = "├" + "┼".join("─" * (w + 2) for w in widths) + "┤"
    bot = "╰" + "┴".join("─" * (w + 2) for w in widths) + "╯"
    head_cells = [C.wrap(h, C.BOLD, accent) for h in headers]
    lines = [C.wrap(top, accent), fmt_row(head_cells), C.wrap(sep, accent)]
    for r in rows:
        lines.append(fmt_row([str(c) for c in r]))
    lines.append(C.wrap(bot, accent))
    return "\n".join(lines)


def spinner_burst(msg: str, ticks: int = 10, delay: float = 0.02) -> None:
    frames = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"
    for i in range(ticks):
        sys.stdout.write(f"\r{C.wrap(frames[i % len(frames)], C.FG_CYAN)} {C.DIM}{msg}{C.RESET}")
        sys.stdout.flush()
        time.sleep(delay)
    sys.stdout.write("\r" + " " * (len(msg) + 4) + "\r")


def typewriter(text: str, delay: float = 0.006, color: str = C.FG_WHITE) -> None:
    for ch in text:
        sys.stdout.write(C.wrap(ch, color))
        sys.stdout.flush()
        time.sleep(delay)
    print()


# ============================================================================
# SECTION 1 — ADVANCED TELEMETRY SIMULATION (Litho / Etch / CVD)
# ============================================================================

class ToolState(Enum):
    RUN = "RUN"
    IDLE = "IDLE"
    PM = "PM"        # preventive maintenance
    DOWN = "DOWN"     # unplanned excursion


@dataclass
class ToolNode:
    """A single fab tool (workstation) in the process flow."""
    tool_id: str
    tool_type: str          # LITHO / ETCH / CVD
    model: str
    theoretical_cycle_min: float   # raw process time per lot (min)
    bay: str
    state: ToolState = ToolState.RUN
    oee_pct: float = 0.0
    q_time_min: float = 0.0
    wip_lots: int = 0
    mtbf_hr: float = 0.0
    mttr_hr: float = 0.0

    @property
    def x_factor(self) -> float:
        """X-factor = actual cycle time / theoretical (raw) process time.
        The single most-watched cadence metric on a fab floor."""
        actual = self.theoretical_cycle_min + self.q_time_min
        return round(actual / self.theoretical_cycle_min, 2)


@dataclass
class WipLot:
    lot_id: str
    product: str
    wafers: int
    priority: str
    current_step: str
    tool_id: str
    q_time_min: float


class TelemetrySimulator:
    """
    Generates a physically-plausible live snapshot of fab WIP across the
    three critical modules named in the S2 problem statement: Lithography
    (EUV/DUV scanners), Plasma Etch, and CVD deposition.
    """

    TOOLSETS = [
        ("LITHO", "ASML TWINSCAN NXE:3600D (EUV)", "Bay-3 EUV Pod", 46.0),
        ("LITHO", "ASML TWINSCAN NXT:2000i (DUV)", "Bay-3 DUV Pod", 31.5),
        ("ETCH",  "Lam Research Kiyo® FX Conductor", "Bay-5 Etch Pod", 18.2),
        ("ETCH",  "Applied Materials Centura® AP",   "Bay-5 Etch Pod", 21.7),
        ("CVD",   "Applied Materials Producer® GT",   "Bay-6 Dep Pod", 27.4),
        ("CVD",   "ASM A412™ Advance Dielectric",     "Bay-6 Dep Pod", 24.9),
    ]

    PRODUCTS = ["N3E-SoC-RevC", "HBM4-Logic-Die", "RF-FEM-22nm", "N5P-AI-Accel"]
    PRIORITIES = ["HOT-LOT", "STD", "STD", "ENG-SPLIT"]

    def __init__(self, seed: int = 2026):
        self.rng = random.Random(seed)
        self.tools: list[ToolNode] = self._spawn_tools()
        self.lots: list[WipLot] = self._spawn_lots()

    def _spawn_tools(self) -> list[ToolNode]:
        tools = []
        for idx, (ttype, model, bay, cyc) in enumerate(self.TOOLSETS):
            state_roll = self.rng.random()
            state = ToolState.RUN
            if state_roll > 0.92:
                state = ToolState.DOWN
            elif state_roll > 0.80:
                state = ToolState.PM

            # Etch is deliberately modeled as the constrained module for the
            # demo narrative: elevated queue times relative to raw process time.
            base_q = {
                "LITHO": self.rng.uniform(15, 55),
                "ETCH": self.rng.uniform(55, 145),
                "CVD": self.rng.uniform(10, 40),
            }[ttype]

            if state == ToolState.DOWN:
                base_q *= self.rng.uniform(2.2, 3.4)
            elif state == ToolState.PM:
                base_q *= self.rng.uniform(1.3, 1.8)

            tools.append(ToolNode(
                tool_id=f"{ttype[:2]}-{idx+1:02d}",
                tool_type=ttype,
                model=model,
                theoretical_cycle_min=cyc,
                bay=bay,
                state=state,
                oee_pct=round(self.rng.uniform(58, 91) if state == ToolState.RUN
                              else self.rng.uniform(0, 40), 1),
                q_time_min=round(base_q, 1),
                wip_lots=self.rng.randint(4, 28),
                mtbf_hr=round(self.rng.uniform(180, 640), 1),
                mttr_hr=round(self.rng.uniform(1.5, 9.5), 1),
            ))
        return tools

    def _spawn_lots(self) -> list[WipLot]:
        lots = []
        for i in range(9):
            tool = self.rng.choice(self.tools)
            lots.append(WipLot(
                lot_id=f"LOT-{2600 + i}",
                product=self.rng.choice(self.PRODUCTS),
                wafers=25,
                priority=self.rng.choice(self.PRIORITIES),
                current_step=f"{tool.tool_type}-STEP-{self.rng.randint(1,9)}",
                tool_id=tool.tool_id,
                q_time_min=round(self.rng.uniform(5, 180), 1),
            ))
        return lots

    def render_dashboard(self) -> str:
        rows = []
        for t in self.tools:
            state_color = {
                ToolState.RUN: C.FG_GREEN,
                ToolState.IDLE: C.FG_GREY,
                ToolState.PM: C.FG_AMBER,
                ToolState.DOWN: C.FG_RED,
            }[t.state]
            xf_color = C.FG_RED if t.x_factor >= 3.0 else (C.FG_AMBER if t.x_factor >= 2.0 else C.FG_GREEN)
            rows.append([
                C.wrap(t.tool_id, C.BOLD),
                t.model,
                C.wrap(t.state.value, C.BOLD, state_color),
                f"{t.oee_pct}%",
                f"{t.q_time_min}m",
                C.wrap(f"{t.x_factor}x", C.BOLD, xf_color),
                str(t.wip_lots),
            ])
        return table(
            ["TOOL", "MODEL", "STATE", "OEE", "Q-TIME", "X-FACTOR", "WIP"],
            rows,
        )

    def render_lot_stream(self) -> str:
        rows = []
        for lot in self.lots:
            pcolor = C.FG_RED if lot.priority == "HOT-LOT" else C.FG_GREY
            rows.append([
                C.wrap(lot.lot_id, C.FG_CYAN),
                lot.product,
                C.wrap(lot.priority, C.BOLD, pcolor),
                lot.current_step,
                lot.tool_id,
                f"{lot.q_time_min}m",
            ])
        return table(["LOT ID", "PRODUCT", "PRIORITY", "STEP", "TOOL", "Q-TIME"], rows)


# ============================================================================
# SECTION 2 — PREDICTIVE BOTTLENECK ENGINE
# ============================================================================

@dataclass
class BottleneckAlert:
    tool_id: str
    tool_type: str
    model: str
    x_factor: float
    severity: str
    root_cause: str
    downstream_delay_days: float
    eta_shift_weeks: float
    confidence_pct: float


class BottleneckEngine:
    """
    Applies fab-standard operational thresholds to the live telemetry
    snapshot and projects the delay forward through downstream assembly,
    test, and shipment — up to a 52-week finished-goods horizon.

    Threshold model (industry-referenced heuristics):
        X-factor < 2.0        -> nominal
        2.0 <= X-factor < 3.0 -> WATCH   (early bottleneck signature)
        3.0 <= X-factor < 4.5 -> WARNING (active constraint, expedite)
        X-factor >= 4.5       -> CRITICAL (line-down risk, escalate to Bob)
    """

    X_WATCH = 2.0
    X_WARN = 3.0
    X_CRIT = 4.5

    # Days of downstream buffer consumed per excess X-factor point,
    # calibrated against typical 60-90 day fab-to-finished-goods cycle.
    DELAY_COEFFICIENT_DAYS = 6.5

    ROOT_CAUSES = {
        "LITHO": "EUV pellicle degradation + reticle qualification backlog",
        "ETCH": "Plasma chamber matching drift across parallel Kiyo/Centura modules",
        "CVD": "Precursor gas-line contamination flagged during in-situ QC",
    }

    def __init__(self, telemetry: TelemetrySimulator):
        self.telemetry = telemetry

    def scan(self) -> list[BottleneckAlert]:
        alerts = []
        for tool in self.telemetry.tools:
            xf = tool.x_factor
            if xf < self.X_WATCH and tool.state != ToolState.DOWN:
                continue

            if tool.state == ToolState.DOWN or xf >= self.X_CRIT:
                severity = "CRITICAL"
                conf = 96.0
            elif xf >= self.X_WARN:
                severity = "WARNING"
                conf = 90.0
            else:
                severity = "WATCH"
                conf = 78.0

            excess = max(xf - 1.0, 0.2)
            downstream_delay_days = round(excess * self.DELAY_COEFFICIENT_DAYS, 1)
            eta_shift_weeks = round(min(downstream_delay_days / 7.0 * self._fanout(tool), 52.0), 1)

            alerts.append(BottleneckAlert(
                tool_id=tool.tool_id,
                tool_type=tool.tool_type,
                model=tool.model,
                x_factor=xf,
                severity=severity,
                root_cause=self.ROOT_CAUSES.get(tool.tool_type, "Unclassified excursion"),
                downstream_delay_days=downstream_delay_days,
                eta_shift_weeks=eta_shift_weeks,
                confidence_pct=conf,
            ))
        alerts.sort(key=lambda a: {"CRITICAL": 0, "WARNING": 1, "WATCH": 2}[a.severity])
        return alerts

    @staticmethod
    def _fanout(tool: ToolNode) -> float:
        """Downstream fan-out multiplier: a delay at a shared/bottleneck
        module (high WIP count) propagates across more downstream lots."""
        return round(1.0 + (tool.wip_lots / 20.0), 2)

    def render(self, alerts: list[BottleneckAlert]) -> str:
        if not alerts:
            return panel("PREDICTIVE BOTTLENECK ENGINE", ["✔ All modules nominal — no X-factor breaches detected."], C.FG_GREEN, "✔")

        rows = []
        for a in alerts:
            scolor = {"CRITICAL": C.FG_RED, "WARNING": C.FG_AMBER, "WATCH": C.FG_BLUE}[a.severity]
            rows.append([
                C.wrap(a.tool_id, C.BOLD),
                a.tool_type,
                C.wrap(a.severity, C.BOLD, scolor),
                f"{a.x_factor}x",
                f"{a.downstream_delay_days}d",
                C.wrap(f"+{a.eta_shift_weeks} wk", C.BOLD, scolor),
                f"{a.confidence_pct}%",
            ])
        body = table(["TOOL", "MODULE", "SEVERITY", "X-FACTOR", "DELAY", "ETA SHIFT", "CONF."], rows)
        crit = [a for a in alerts if a.severity == "CRITICAL"]
        footer = ""
        if crit:
            worst = max(crit, key=lambda a: a.eta_shift_weeks)
            footer = (f"\n{C.wrap('⚠ HIGHEST-IMPACT PATH:', C.BOLD, C.FG_RED)} {worst.tool_id} "
                      f"({worst.model}) — {worst.root_cause}. "
                      f"Projected finished-goods ETA slip: "
                      f"{C.wrap(f'{worst.eta_shift_weeks} weeks', C.BOLD, C.FG_RED)} "
                      f"(of 52-week horizon), confidence {worst.confidence_pct}%.")
        return body + footer


# ============================================================================
# SECTION 3 — GEOPOLITICAL GEOGRAPHIC RISK MATRIX
# ============================================================================

@dataclass
class MaterialRisk:
    material: str
    use_case: str
    china_share_pct: float
    hhi_score: int              # Herfindahl-Hirschman Index (supply concentration)
    export_control_active: bool
    alt_source_lead_weeks: int
    risk_tier: str = ""
    risk_score: int = 0


class GeopoliticalMatrix:
    """
    Scores single-source / concentrated-source material dependencies
    against active export-control posture. Modeled on real 2023-2025
    critical-mineral exposure for advanced-node semiconductor supply
    chains (gallium & germanium export licensing; neon gas concentration
    from Eastern-European electrolytic byproduct streams).
    """

    MATERIALS = [
        ("Gallium", "III-V epitaxy, RF power amps, GaN substrates", 82.0, 6900, True, 24),
        ("Germanium", "IR optics, SiGe transistors, fiber-optic substrates", 68.0, 5400, True, 20),
        ("Neon (electronic grade)", "Excimer laser gas mix for DUV lithography scanners", 35.0, 3100, False, 14),
        ("Palladium", "Interconnect plating, wire-bond alternatives", 41.0, 2800, False, 10),
        ("Tungsten", "Contact plugs, interconnect barrier layers", 58.0, 4200, False, 16),
    ]

    def assess(self) -> list[MaterialRisk]:
        results = []
        for name, use, share, hhi, ctrl, lead in self.MATERIALS:
            score = 0
            score += min(share, 100) * 0.5
            score += (hhi / 10000) * 100 * 0.3
            score += (20 if ctrl else 0)
            score += min(lead, 30) * 0.5
            score = round(score)
            tier = "SEVERE" if score >= 70 else "ELEVATED" if score >= 50 else "MODERATE"
            results.append(MaterialRisk(name, use, share, hhi, ctrl, lead, tier, score))
        results.sort(key=lambda m: -m.risk_score)
        return results

    def render(self, risks: list[MaterialRisk]) -> str:
        rows = []
        for r in risks:
            tcolor = {"SEVERE": C.FG_RED, "ELEVATED": C.FG_AMBER, "MODERATE": C.FG_BLUE}[r.risk_tier]
            ctrl_flag = C.wrap("● ACTIVE", C.BOLD, C.FG_RED) if r.export_control_active else C.wrap("○ none", C.FG_GREY)
            rows.append([
                C.wrap(r.material, C.BOLD),
                f"{r.china_share_pct:.0f}%",
                str(r.hhi_score),
                ctrl_flag,
                f"{r.alt_source_lead_weeks}wk",
                C.wrap(f"{r.risk_score}/100 {r.risk_tier}", C.BOLD, tcolor),
            ])
        return table(["MATERIAL", "CN SHARE", "HHI", "EXPORT CTRL", "ALT LEAD", "RISK SCORE"], rows)


# ============================================================================
# SECTION 4 — MCP TOOL SERVER (exposed to the IBM Bob Agent)
# ============================================================================

class ChronoChipMCPServer:
    """
    Minimal, protocol-faithful MCP tool registry. In production this class's
    `tools` dict maps 1:1 onto an MCP server's `tools/list` + `tools/call`
    surface; here it is invoked in-process by BobAgent to keep the hackathon
    prototype dependency-free while remaining structurally identical to a
    real MCP stdio/SSE deployment.
    """

    def __init__(self):
        self.telemetry = TelemetrySimulator()
        self.bottleneck_engine = BottleneckEngine(self.telemetry)
        self.geo_matrix = GeopoliticalMatrix()
        self.tools: dict[str, Callable] = {
            "fab.get_wip_telemetry": self.get_wip_telemetry,
            "fab.predict_bottleneck": self.predict_bottleneck,
            "geo.assess_material_risk": self.assess_material_risk,
        }

    def get_wip_telemetry(self) -> dict:
        return {
            "tool_count": len(self.telemetry.tools),
            "active_lots": len(self.telemetry.lots),
            "down_tools": [t.tool_id for t in self.telemetry.tools if t.state == ToolState.DOWN],
            "avg_x_factor": round(sum(t.x_factor for t in self.telemetry.tools) / len(self.telemetry.tools), 2),
        }

    def predict_bottleneck(self) -> list[BottleneckAlert]:
        return self.bottleneck_engine.scan()

    def assess_material_risk(self) -> list[MaterialRisk]:
        return self.geo_matrix.assess()


# ============================================================================
# SECTION 5 — IBM BOB CONVERSATIONAL AGENT (CLI subagent persona)
# ============================================================================

class BobAgent:
    """
    A lightweight rules-over-telemetry NLU layer standing in for the IBM
    Bob orchestration runtime. In the real deployment, Bob's LLM planner
    calls the MCP tools above and composes the narrative; here that same
    call -> synthesize -> respond loop is implemented explicitly so the
    demo is fully deterministic and narration-safe for a live video.
    """

    def __init__(self, server: ChronoChipMCPServer):
        self.server = server

    def answer(self, query: str) -> str:
        q = query.lower().strip()

        if any(k in q for k in ["bottleneck", "delay", "late", "slip", "eta"]):
            return self._answer_bottleneck()
        if any(k in q for k in ["gallium", "neon", "germanium", "geopolitic", "china", "export", "risk", "material", "supply"]):
            return self._answer_geo()
        if any(k in q for k in ["wip", "queue", "status", "tool", "fab", "litho", "etch", "cvd", "health"]):
            return self._answer_wip()
        if any(k in q for k in ["summary", "brief", "report", "overall", "exec"]):
            return self._answer_summary()
        return self._answer_fallback()

    def _answer_wip(self) -> str:
        snap = self.server.get_wip_telemetry()
        down = ", ".join(snap["down_tools"]) if snap["down_tools"] else "none"
        return (
            f"Live WIP snapshot across {snap['tool_count']} monitored tools and "
            f"{snap['active_lots']} priority lots. Fleet-average X-factor is "
            f"{C.wrap(str(snap['avg_x_factor']) + 'x', C.BOLD, C.FG_AMBER)}. "
            f"Tools currently DOWN: {C.wrap(down, C.BOLD, C.FG_RED if snap['down_tools'] else C.FG_GREEN)}.\n"
            f"{self.server.telemetry.render_dashboard()}"
        )

    def _answer_bottleneck(self) -> str:
        alerts = self.server.predict_bottleneck()
        rendered = self.server.bottleneck_engine.render(alerts)
        if not alerts:
            return "No active constraint signatures — floor is running within operational cadence.\n" + rendered
        crit = [a for a in alerts if a.severity == "CRITICAL"]
        lead = crit[0] if crit else alerts[0]
        narrative = (
            f"I'm tracking {len(alerts)} active constraint signature(s). The highest-impact path is "
            f"{C.wrap(lead.tool_id, C.BOLD)} ({lead.model}) running at "
            f"{C.wrap(str(lead.x_factor) + 'x', C.BOLD, C.FG_RED)} X-factor — "
            f"{lead.root_cause}. Left uncorrected, I project a "
            f"{C.wrap(f'+{lead.eta_shift_weeks}-week', C.BOLD, C.FG_RED)} shift to finished-goods ETA "
            f"at {lead.confidence_pct}% confidence.\n"
        )
        return narrative + rendered

    def _answer_geo(self) -> str:
        risks = self.server.assess_material_risk()
        rendered = self.server.geo_matrix.render(risks)
        severe = [r for r in risks if r.risk_tier == "SEVERE"]
        if severe:
            names = ", ".join(r.material for r in severe)
            narrative = (
                f"{len(severe)} material(s) are flagged SEVERE: {C.wrap(names, C.BOLD, C.FG_RED)}. "
                f"These sit above 60% concentrated-origin share with active export-control posture — "
                f"recommend dual-sourcing qualification to start immediately; typical alt-source "
                f"qualification lead time runs {max(r.alt_source_lead_weeks for r in severe)} weeks.\n"
            )
        else:
            narrative = "No materials in the SEVERE tier this cycle, but elevated-tier exposure still warrants hedging.\n"
        return narrative + rendered

    def _answer_summary(self) -> str:
        snap = self.server.get_wip_telemetry()
        alerts = self.server.predict_bottleneck()
        risks = self.server.assess_material_risk()
        worst_alert = max(alerts, key=lambda a: a.eta_shift_weeks) if alerts else None
        worst_risk = risks[0]
        lines = [
            f"Fleet X-factor avg: {C.wrap(str(snap['avg_x_factor']) + 'x', C.BOLD, C.FG_AMBER)}  |  "
            f"Tools DOWN: {C.wrap(str(len(snap['down_tools'])), C.BOLD)}  |  "
            f"Active alerts: {C.wrap(str(len(alerts)), C.BOLD)}",
        ]
        if worst_alert:
            lines.append(
                f"Top schedule risk: {worst_alert.tool_id} ({worst_alert.tool_type}) — "
                f"projected +{worst_alert.eta_shift_weeks}wk ETA shift."
            )
        lines.append(
            f"Top supply risk: {worst_risk.material} — {worst_risk.risk_score}/100 ({worst_risk.risk_tier})."
        )
        return panel("BOB EXECUTIVE BRIEF", lines, C.FG_INDIGO, "◆")

    def _answer_fallback(self) -> str:
        return (
            "I can help with fab WIP status, bottleneck/ETA predictions, geopolitical material "
            "risk, or an executive summary. Try: 'what's my biggest bottleneck risk?', "
            "'show gallium exposure', or 'give me the exec summary'."
        )


# ============================================================================
# SECTION 6 — DEMO ORCHESTRATION / MAIN CLI LOOP
# ============================================================================

BANNER = r"""
   ▄████████    ▄█    █▄     ▄████████    ▄██████▄  ███▄▄▄▄▄    ▄██████▄
  ███    ███   ███    ███   ███    ███   ███    ███ ███▀▀▀██▄ ███    ███
  ███    █▀    ███    ███   ███    ███   ███    ███ ███   ███ ███    ███
 ▄███▄▄▄       ███    ███  ▄███▄▄▄▄██▀   ███    ███ ███   ███ ███    ███
▀▀███▀▀▀       ███    ███ ▀▀███▀▀▀▀▀   ▀ ███    ███ ███   ███ ███    ███
  ███          ███    ███ ▀███████████   ███    ███ ███   ███ ███    ███
  ███          ███    ███   ███    ███   ███    ███ ███   ███ ███    ███
  ███           ▀██████▀    ███    ███    ▀██████▀   ▀█   █▀   ▀██████▀
                             ███    ███
        C H R O N O C H I P   A I   ::  S M A R T   F A B   C O P I L O T
"""


def print_banner() -> None:
    print(C.wrap(BANNER, C.BOLD, C.FG_CYAN))
    sub = "  Smart Fab & Geopolitical Risk Copilot  |  IBM Bob Innovation Hackathon 2026  |  Problem Statement S2"
    print(C.wrap(sub.center(term_width()), C.FG_GREY, C.ITALIC))
    print(hr("═", C.FG_INDIGO))


def boot_sequence() -> ChronoChipMCPServer:
    steps = [
        "Establishing MCP transport with IBM Bob orchestration runtime",
        "Registering tools: fab.get_wip_telemetry, fab.predict_bottleneck, geo.assess_material_risk",
        "Attaching to fab historian stream (Litho / Etch / CVD telemetry)",
        "Calibrating X-factor thresholds against operational baseline",
        "Loading geopolitical supply-concentration reference set (HHI model)",
        "Handshake complete — Bob subagent is live",
    ]
    for s in steps:
        spinner_burst(s, ticks=8, delay=0.015)
        print(f"{C.wrap('✔', C.BOLD, C.FG_GREEN)} {C.FG_GREY}{s}{C.RESET}")
    print()
    return ChronoChipMCPServer()


def run_scripted_demo(bob: BobAgent) -> None:
    print(hr())
    print(panel("SESSION CONTEXT", [
        f"Operator: Fab Operations Director   |   Session start: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "Agent: IBM Bob (ChronoChip AI subagent)   |   Fab: FAB-14 (300mm, Logic/RF)",
    ], C.FG_BLUE, "🛰"))
    print()

    scripted = [
        "Bob, give me current fab health and WIP status.",
        "Do we have any predictive bottleneck alerts I should escalate?",
        "What is our geopolitical exposure on gallium and neon right now?",
        "Give me the executive summary for the 9am standup.",
    ]

    for query in scripted:
        print(C.wrap(f"\n▶ Fab Ops Director:", C.BOLD, C.FG_WHITE), query)
        spinner_burst("Bob is querying MCP tools + reasoning over telemetry", ticks=14, delay=0.02)
        print(C.wrap("◆ IBM Bob:", C.BOLD, C.FG_MAGENTA))
        print(bob.answer(query))
        print(hr("┈", C.FG_GREY))
        time.sleep(0.1)


def interactive_loop(bob: BobAgent) -> None:
    print()
    print(panel(
        "INTERACTIVE MODE",
        ["Ask Bob about WIP status, bottlenecks/ETA risk, or geopolitical material exposure.",
         "Type 'summary' for the exec brief, or 'exit' to end the session."],
        C.FG_TEAL, "⌨",
    ))
    while True:
        try:
            query = input(C.wrap("\n▶ Fab Ops Director › ", C.BOLD, C.FG_WHITE))
        except (EOFError, KeyboardInterrupt):
            print("\n" + C.wrap("Session terminated.", C.FG_GREY))
            break
        if not query.strip():
            continue
        if query.strip().lower() in {"exit", "quit", "q"}:
            print(C.wrap("◆ IBM Bob:", C.BOLD, C.FG_MAGENTA), "Session closed. Handing control back to the fab MES.")
            break
        spinner_burst("Bob is querying MCP tools + reasoning over telemetry", ticks=10, delay=0.015)
        print(C.wrap("◆ IBM Bob:", C.BOLD, C.FG_MAGENTA))
        print(bob.answer(query))


def main() -> None:
    print_banner()
    server = boot_sequence()
    bob = BobAgent(server)

    print(panel("MCP TOOL REGISTRY", [
        f"{C.wrap('•', C.FG_TEAL)} fab.get_wip_telemetry     — live WIP across Litho / Etch / CVD",
        f"{C.wrap('•', C.FG_TEAL)} fab.predict_bottleneck    — X-factor breach detection + 52wk ETA projection",
        f"{C.wrap('•', C.FG_TEAL)} geo.assess_material_risk  — single-source HHI risk matrix (Ga / Ne / Ge / Pd / W)",
    ], C.FG_CYAN, "⚙"))

    run_scripted_demo(bob)

    if "--no-interactive" not in sys.argv:
        interactive_loop(bob)


if __name__ == "__main__":
    main()
